export const dogBreeds = [
   "Airedale Terrier 🐕",
   "Akita 🐕",
   "Alaskan Malamute 🐕",
   "American Bulldog 🐕",
   "Australian Shepherd 🐕",
   "Beagle 🐕",
   "Bernese Mountain Dog 🐕",
   "Bichon Frise 🐕",
   "Border Collie 🐕",
   "Boxer 🐕",
   "Bulldog 🐕",
   "Cavalier King Charles Spaniel 🐕",
   "Chihuahua 🐕",
   "Chow Chow 🐕",
   "Cocker Spaniel 🐕",
   "Dachshund 🐕",
   "Dalmatian 🐕",
   "Doberman Pinscher 🐕",
   "English Bulldog 🐕",
   "French Bulldog 🐕",
   "German Shepherd 🐕",
   "Golden Retriever 🐕",
   "Great Dane 🐕",
   "Greyhound 🐕",
   "Havanese 🐕",
   "Husky 🐕",
   "Labrador Retriever 🐕",
   "Maltese 🐕",
   "Mastiff 🐕",
   "Miniature Schnauzer 🐕",
   "Pomeranian 🐕",
   "Poodle 🐕",
   "Pug 🐕",
   "Rottweiler 🐕",
   "Saint Bernard 🐕",
   "Shetland Sheepdog 🐕",
   "Shih Tzu 🐕",
   "Siberian Husky 🐕",
   "Staffordshire Bull Terrier 🐕",
   "Weimaraner 🐕",
   "West Highland White Terrier 🐕",
   "Yorkshire Terrier 🐕"
 ];
