export const Users = [
   {
      name: 'John Taiwo',
      email: 'johntaiwo@gmail.com',
      date: '10-02-24 - 10:00AM',
      breed: 'Bull dog',
      comment: 'Dog is allergic to chicken',
      address: 'Ikeja, Lagos',
      status: 'confirmed',
   },
   {
      name: 'Gabriel Fish',
      email: 'gabrielfish@gmail.com',
      date: '10-02-24 - 10:00AM',
      breed: 'Poddle',
      comment: 'Dog is anxious around others',
      address: 'Ikeja, Lagos',
      status: 'pending',
   },
   {
      name: 'Mathew Doe',
      email: 'matthewdoe@gmail.com',
      date: '10-02-24 - 10:00AM',
      breed: 'Beagle',
      comment: 'Client prefers early morning',
      address: 'Ikeja, Lagos',
      status: 'confirmed',
   },
   {
      name: 'Peter Femi',
      email: 'peterfemi@gmail.com',
      date: '10-02-24 - 10:00AM',
      breed: 'Shin Tzu',
      comment: 'Dog mates too much',
      address: 'Ikeja, Lagos',
      status: 'pending',
   },
   {
      name: 'Tope Mike',
      email: 'topemike@gmail.com',
      date: '10-02-24 - 10:00AM',
      breed: 'Boxer',
      comment: 'Dog is allergic to chicken',
      address: 'Ikeja, Lagos',
      status: 'confirmed',
   },
]